export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_FAILURE = "USERS_FAILURE";

export const TOTAL_USERS_REQUEST = "TOTAL_USERS_REQUEST";
export const TOTAL_USERS_SUCCESS = "TOTAL_USERS_SUCCESS";
export const TOTAL_USERS_FAILURE = "TOTAL_USERS_FAILURE";

export const USERS_SORT_REQUEST = "USERS_SORT";
export const USERS_SORT_SUCCESS = "USERS_SORT_SUCCESS"
export const USERS_SORT_FAILURE = "USERS_SORT_FAILURE"

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS"
export const USER_ADD_FAILURE = "USER_ADD_FAILURE"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE"

export const USER_UPLOAD_IMAGE_REQUEST = "USER_UPLOAD_IMAGE_REQUEST";
export const USER_UPLOAD_IMAGE_SUCCESS = "USER_UPLOAD_IMAGE_SUCCESS"
export const USER_UPLOAD_IMAGE_FAILURE = "USER_UPLOAD_IMAGE_FAILURE"